export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_SINGLE_PRODUCT = 'SET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';

